### ISSUE TITLE
Unable to make overleaf-registration  work

### ISSUE THREAD

**Issue by cosmicbeams** [StudentiUniMi/overleaf-registration#3]
Hello,

First off, thank you for the work you have done.
I'm trying to set this up but nothing seems to be working.

**docker-compose.yml:**
```
version: '3'

networks:
  traefik_net:
    external: true

services:
  overleaf-registration:
    image: ghcr.io/studentiunimi/overleaf-registration
    container_name: overleaf-registration
    environment:
      CAPTCHA_SERVER_KEY: 6LdUWT4qAAAAAM8Zr5l-Ak1KizgXhgoXlMiWBAom
      CAPTCHA_CLIENT_KEY: 6LdUWT4qAAAAAPVISfT18MbRuOHVY8-ewyDuXiM-
      OF_INSTANCE: ''
      OF_ADMIN_EMAIL: '*******'
      OF_ADMIN_PASSWORD: '*******!'
    networks:
      - traefik_net
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.overleaf-registration.loadbalancer.server.port=8000"
```

For the variable OF_INSTANCE I tried to set the ID of the docker container sharelatex and the url of the overleaf frontend, but neither worked.

**docker ps:**
```
CONTAINER ID   IMAGE                         COMMAND                  CREATED       STATUS                 PORTS                     NAMES
**ea7957873908**   sharelatex/sharelatex:5.1.1   "/sbin/my_init"          13 days ago   Up 10 days             10.194.64.83:80->80/tcp   sharelatex
31bf7c16d8c6   redis:6.2                     "docker-entrypoint.s…"   13 days ago   Up 10 days             6379/tcp                  redis
9996ac77e21b   mongo:6.0                     "docker-entrypoint.s…"   13 days ago   Up 10 days (healthy)   27017/tcp                 mongo
```

Please help me to see clearer.
